# Generated by Django 2.0.3 on 2018-04-21 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('cast', models.TextField(max_length=500)),
                ('duration', models.FloatField()),
                ('poster', models.ImageField(max_length=500, upload_to='poster')),
                ('city_id', models.ManyToManyField(to='listmovie.City')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.Language')),
            ],
        ),
        migrations.CreateModel(
            name='MovieShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_start', models.TimeField()),
                ('show_end', models.TimeField()),
                ('date', models.DateField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.Movie')),
            ],
            options={
                'ordering': ['show_start'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_seats_booked', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=10)),
                ('reservation_booking_date', models.DateField(default='2018-04-08')),
                ('movie_show_date', models.DateField(default='2018-04-08')),
                ('tranction_id', models.UUIDField()),
                ('movie_show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.MovieShow')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_start', models.TimeField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_code', models.CharField(default='1_1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SeatingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeatReserved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.Reservation')),
                ('seat_id', models.ManyToManyField(to='listmovie.Seat')),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('no_of_seats', models.IntegerField()),
                ('address', models.TextField(max_length=500)),
                ('seating_arrangement', models.TextField(max_length=2000, null=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.City')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.Movie')),
                ('seating_category', models.ManyToManyField(default=None, to='listmovie.SeatingCategory')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='theatre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.Theatre'),
        ),
        migrations.AddField(
            model_name='screening',
            name='seating_category',
            field=models.ManyToManyField(to='listmovie.SeatingCategory'),
        ),
        migrations.AddField(
            model_name='screening',
            name='theatre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.Theatre'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.ReservationType'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_id',
            field=models.ManyToManyField(to='listmovie.Seat'),
        ),
        migrations.AddField(
            model_name='movieshow',
            name='theatre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.Theatre'),
        ),
    ]
