# Generated by Django 2.0.3 on 2018-04-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listmovie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='screening',
            name='seating_category',
            field=models.ManyToManyField(to='listmovie.SeatingCategory'),
        ),
    ]
