# Generated by Django 2.0.3 on 2018-04-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listmovie', '0002_auto_20180407_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='seating_arrangement',
            field=models.TextField(default=None, max_length=2000),
        ),
    ]
