# Generated by Django 2.0.3 on 2018-04-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listmovie', '0003_reservation_no_of_seats_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='seat_id',
            field=models.ManyToManyField(to='listmovie.Seat'),
        ),
    ]
