# Generated by Django 2.0.3 on 2018-04-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listmovie', '0003_theatre_seating_arrangement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='seating_arrangement',
        ),
    ]
