# Generated by Django 2.0.3 on 2018-04-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listmovie', '0004_remove_theatre_seating_arrangement'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='seating_arrangement',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
