# Generated by Django 2.0.3 on 2018-04-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listmovie', '0007_auto_20180407_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('theatre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.Theatre')),
            ],
        ),
    ]
