# Generated by Django 2.0.3 on 2018-04-08 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listmovie', '0008_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_start', models.TimeField()),
                ('show_end', models.TimeField()),
                ('date', models.DateField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.Movie')),
                ('theatre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.Theatre')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeatReserved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.Reservation')),
                ('screening_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.Screening')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.Seat')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.ReservationType'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='screening_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listmovie.Screening'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
